spring.application.name=librarymanagement
# Application settings
server.port=8082
# Feign client configuration
feign.client.config.default.connect-timeout=5000       # Connection timeout (ms)
feign.client.config.default.read-timeout=5000          # Read timeout (ms)

spring.data.redis.host = redis
spring.data.redis.port = 6060


# Base URL for the book-service (used by the Feign client)
#book-service.url=http://localhost:8081- this will not work when you run container as localhost refers to container and not the host system
book-service.url=http://host.docker.internal:8081
# Enable Feign client logging (optional)
logging.level.feign=DEBUG

